# Docker-compose configuration for development

version: '3'

services:
    django:
        build:
            context: .
            dockerfile: Dockerfile-django
        ports:
            - "3000:80"
        volumes:
            - "./knowledge_graphql_microservices:/app"
            - ".data/media:/files/media"
        environment:
            - PYTHONUNBUFFERED=0
        # Add -Wall option to see the (deprecation) warnings
        # command: python -Wall manage.py runserver 0.0.0.0:80
        command: python manage.py runserver 0.0.0.0:80
        entrypoint: /usr/bin/wait-for-it.sh postgres:5432 -t 60 --
        depends_on:
            - postgres
            - redis
            - mailhog

    frontend:
        build:
            context: .
            dockerfile: Dockerfile-node
        ports:
            - "8000:8000"
            - "8001:8001"
        volumes:
            - "./app:/app"
            - ".data/node_modules:/app/node_modules"
        depends_on:
            - django

    postgres:
        image: postgres:10
        volumes:
            - ".data/postgres:/var/lib/postgresql/data"
        environment:
            POSTGRES_USER: knowledge_graphql_microservices
            POSTGRES_PASSWORD: knowledge_graphql_microservices

    mongodb:
        image: mongo:4.0-xenial
        environment:
            MONGO_INITDB_DATABASE: knowledge_graphql_microservices
            MONGO_INITDB_ROOT_USERNAME: knowledge_graphql_microservices
            MONGO_INITDB_ROOT_PASSWORD: knowledge_graphql_microservices
            MONGODB_DATA_DIR: /data/db
            MONDODB_LOG_DIR: /dev/null
        ports:
            - "27017-27019:27017-27019"
        volumes:
            - ".data/mongodb:/data/db"

    redis:
        image: redis:4.0.10-alpine
        sysctls:
            # To allow maintaining TCP backlog setting that defaults to 511
            net.core.somaxconn: 512
        volumes:
            - ".data/redis:/data"

    mailhog:
        image: mailhog/mailhog:v1.0.0
        ports:
            - "8025:8025"
        logging:
            driver: "none"
